---
title: "Changing Large Wildfire Risk in the Southeastern U.S."
date: "2024-02-22"
description: "Global change is altering ecosystem structure and function including natural disturbance processes like fire that can threaten human communities. We assess changes in large (greater than 200 ha) wildfire activity across southeastern U.S…"
categories: ["Presentation"]
pub-authors: "Donovan, V. M., Crandall, R. M., Fill, J. M., Ivey, M. A., **Weidig, N. C.** & Wonkka, C. L."
pub-venue: "Gulf of Mexico Conference"
pub-url: "https://gulfofamericaalliance.org/wp-content/uploads/2024/02/GOMCON-Schedule-of-Concurrent-Sessions-02.14.24.pdf"
---

::: {.nw-cite-meta}
Donovan, V. M., Crandall, R. M., Fill, J. M., Ivey, M. A., **Weidig, N. C.** & Wonkka, C. L. (2024). *Gulf of Mexico Conference*.
:::

[Source](https://gulfofamericaalliance.org/wp-content/uploads/2024/02/GOMCON-Schedule-of-Concurrent-Sessions-02.14.24.pdf){.nw-btn .nw-btn-primary target="_blank"} [BibTeX](cite.bib){.nw-btn .nw-btn-ghost}

## Abstract

Global change is altering ecosystem structure and function including natural disturbance processes like fire that can threaten human communities. We assess changes in large (greater than 200 ha) wildfire activity across southeastern U.S. ecoregions and highlight current lines of investigation for factors that are increasing wildfire risk. We found shifting wildfire regime characteristics across southeastern ecoregions that include increasing wildfire number, size, and annual occurrence, along with changes in wildfire seasonality. More than 25% of wildfires occurred within the wildland-urban interface (WUI), where wildlands meet human development, and thus can pose a heightened risk to communities. However, increases in wildfires in the WUI were not as substantial as those in other areas. Human ignitions started most wildfires in the southeastern U.S., though in the Southern Coastal Plain, the majority of area burned was caused by naturally started wildfires. We also found long-term increases in woody cover across southeastern ecoregions, which has been associated with increasing wildfire risk. While further investigation into the drivers of changing large wildfire patterns are needed, we suggest further application of fuels management and the promotion of fire resistant homes and buildings to enhance community resilience to wildfire.
