---
title: "Changing large wildfire regime dynamics in the eastern United States"
date: "2025-10-01"
description: "Dr. Donovan will provide a summary of her lab’s ongoing research investigations into changes in large (>200 ha) wildfire activity across multiple scales in the eastern U.S. and the interacting factors affecting wildfire risk. Specifically…"
categories: ["Presentation"]
pub-authors: "Donovan, V. M., **Weidig, N. C.**, Ivey, M. A., Crandall, R. M., Fill, J. M. & Wonkka, C. L."
pub-venue: "Oak Woodlands & Forests Fire Consortium"
---

::: {.nw-cite-meta}
Donovan, V. M., **Weidig, N. C.**, Ivey, M. A., Crandall, R. M., Fill, J. M. & Wonkka, C. L. (2025). *Oak Woodlands & Forests Fire Consortium*.
:::

[BibTeX](cite.bib){.nw-btn .nw-btn-ghost}

## Abstract

Dr. Donovan will provide a summary of her lab’s ongoing research investigations into changes in large (>200 ha) wildfire activity across multiple scales in the eastern U.S. and the interacting factors affecting wildfire risk. Specifically, we found shifting wildfire regime characteristics across south and central ecoregions in the east that include increasing wildfire number, size, and annual occurrence, along with changes in wildfire seasonality. Just under half of all wildfires burned within the wildland-urban interface (WUI), where the greatest risk to human life and property from wildfires exists. Increases in large wildfire are largely occurring outside the WUI, though these wildfires tend to be closer to the WUI than expected at random. We find factors such as suppression potential, weather conditions, and patterns in woody cover influence the WUI-wildfire dynamic, but relationships vary regionally. We also identified long-term increases in woody cover across eastern ecoregions, linking higher levels of woody cover to heightened wildfire risk in multiple locations. Further investigations have found that woody cover interactions with short-term drought strongly predict large wildfire occurrence across numerous eastern ecoregions. While further research into the drivers of changing large wildfire patterns is needed, we suggest the strategic application of fuels management along with the development of fire-resistant homes and buildings to enhance community resilience to wildfire in the east.
