---
title: "Southeastern Myotis (Myotis austroriparius) Use of Stormwater Sewer Systems"
date: "2025-04-01"
description: "As urbanization continues, animals are increasingly compelled to navigate human-altered environments. Here we investigate wildlife use of stormwater sewer systems (SSS), a widespread, subterranean environment resulting from urbanization…"
categories: ["Presentation"]
pub-authors: "Ivory II, A. A., Brock, K. M., Johnson, S. A., **Weidig, N. C.**, Hallett, M. T., Acevedo, M. A. & Scheffers, B. R."
pub-venue: "Florida Bat Working Group Annual Meeting; Southeastern Bat Diversity Network"
---

::: {.nw-cite-meta}
Ivory II, A. A., Brock, K. M., Johnson, S. A., **Weidig, N. C.**, Hallett, M. T., Acevedo, M. A. & Scheffers, B. R. (2025). *Florida Bat Working Group Annual Meeting; Southeastern Bat Diversity Network*.
:::

[BibTeX](cite.bib){.nw-btn .nw-btn-ghost}

## Abstract

As urbanization continues, animals are increasingly compelled to navigate human-altered environments. Here we investigate wildlife use of stormwater sewer systems (SSS), a widespread, subterranean environment resulting from urbanization. We used camera traps to reveal how wildlife exploit subterranean pathways, shedding light on their presence within this anthropogenic context in Alachua County, Florida. From February to May 2023, we documented a total of 35 species of vertebrates within SSS, including amphibians, reptiles, and birds, although mammals dominated our sample. Raccoons and Southeastern Myotis accounted for more than half of all observations, signifying their prevalence and widespread presence within SSS. Our research offers a comprehensive exploration of vertebrate diversity within an unconventional urban habitat and provides valuable insights into the relationship between SSS and species utilization patterns. Ultimately, our research lays the groundwork for future studies and informs the development of ecologically conscientious urban planning strategies.
