---
title: "Burning Boundaries: Large Wildfire Patterns and Drivers in the Eastern United States Wildland-Urban Interface"
date: "2025-11-19"
description: "Large wildfires are increasing in the eastern United States, raising concern about the risk to human life and property within the wildland-urban interface (WUI), where development and vegetation intermingle. In this webinar, we will…"
categories: ["Webinar"]
pub-authors: "**Weidig, N. C.**, Wonkka, C. L., Ivey, M. A., Johnson, D. J. & Donovan, V. M."
pub-venue: "Southern Fire Exchange"
pub-url: "https://www.youtube.com/watch?v=HdklLrpJKkM"
---

::: {.nw-cite-meta}
**Weidig, N. C.**, Wonkka, C. L., Ivey, M. A., Johnson, D. J. & Donovan, V. M. (2025). *Southern Fire Exchange*.
:::

[Source](https://www.youtube.com/watch?v=HdklLrpJKkM){.nw-btn .nw-btn-primary target="_blank"} [BibTeX](cite.bib){.nw-btn .nw-btn-ghost}

## Abstract

Large wildfires are increasing in the eastern United States, raising concern about the risk to human life and property within the wildland-urban interface (WUI), where development and vegetation intermingle. In this webinar, we will explore large wildfire patterns inside and outside the WUI and the factors driving these patterns over the past three decades in the eastern U.S. Although the WUI only covers 22% of this region by area, it plays a crucial role in large wildfire dynamics. We found that environmental factors—particularly higher woody cover and drier conditions—and, to a lesser extent, social factors, influence where wildfires occur in and near the WUI. Our findings highlight complex interactions between human development and large wildfire occurrence, as well as the need for proactive fuels management in the East.
