/**
 * Rebuild src/lib/icons.generated.ts from lucide-static.
 *
 * Every UI icon on the site is Lucide (ISC, lucide.dev): one 24px grid, one
 * stroke, one set of terminals. Brand marks are not generated here: they are
 * the SVGs in public/uploads/, loaded by src/lib/brand-icons.ts. Each icon is
 * run through SVGO (shapes to paths, paths merged, path data minified) so the
 * homepage ships as few bytes as possible.
 *
 *   node scripts/generate-icons.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { optimize } from 'svgo';

const require = createRequire(import.meta.url);
const lucideDir = path.join(path.dirname(require.resolve('lucide-static/package.json')), 'icons');

/** site name -> Lucide icon file (icons/<file>.svg) */
const MAP = {
  rss: 'rss',
  mail: 'mail',
  envelope: 'mail',
  message: 'message-square-text',
  calendar: 'calendar-days',
  briefcase: 'briefcase-business',
  school: 'school',
  code: 'code-xml',
  users: 'users',
  sparkles: 'sparkles',
  layers: 'layers',
  trophy: 'trophy',
  bulb: 'lightbulb',
  file: 'file-text',
  pencil: 'pencil',
  help: 'circle-question-mark',
  search: 'search',
  pin: 'map-pin',
  clock: 'clock',
  cube: 'box',
  download: 'download',
  arrow: 'arrow-right',
  chevron: 'chevron-down',
  external: 'external-link',
  sun: 'sun',
  moon: 'moon',
  sunMoon: 'sun-moon',
  menu: 'menu',
  close: 'x',
  satellite: 'satellite',
  chart: 'chart-column',
  ai: 'brain-circuit',
  leaf: 'leaf',
  database: 'database',
  terminal: 'square-terminal',
  quote: 'quote',
  video: 'video',
  news: 'newspaper',
  shield: 'shield-check',
  slides: 'presentation',
  book: 'book-open',
  report: 'clipboard-check',
  preprint: 'file-clock',
  graduationCap: 'graduation-cap',
  check: 'check',
  tag: 'tag',
  copy: 'copy',
  link: 'link',
  hash: 'hash',
  reader: 'book-open-text',
  expand: 'expand',
  zoom: 'zoom-in',
  left: 'chevron-left',
  right: 'chevron-right',
  printer: 'printer',
  filePdf: 'file-down',
  filter: 'list-filter',
  info: 'info',
  pause: 'pause',
  play: 'play',
  circleArrowUp: 'circle-arrow-up',
  rocket: 'rocket',
  ellipsis: 'ellipsis',
  share: 'share-2',
  earth: 'earth',
  cpu: 'cpu',
  broom: 'broom-sparkles',
  flame: 'flame',
  flaskConical: 'flask-conical',
  plug: 'webhook',
  'nav-search': 'search',
  'nav-sun': 'sun',
  'nav-moon': 'moon',
  'nav-sunMoon': 'sun-moon',
  'nav-listFilter': 'list-filter',
  'nav-x': 'x',
  'nav-chevronRight': 'chevron-right',
};

/** The children of the <svg>, whitespace collapsed. Sliced rather than matched:
    a regex spanning the whole file backtracks for no benefit here. */
const inner = (svg) => {
  const open = svg.indexOf('>', svg.indexOf('<svg'));
  const close = svg.lastIndexOf('</svg>');
  return svg
    .slice(open + 1, close)
    .replace(/\s+/g, ' ')
    .replaceAll(' />', '/>')
    .trim();
};

/** Lucide's own attributes, repeated on the wrapper so SVGO sees the same
    context the icon renders in. */
const WRAP =
  'xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

const slim = (body) =>
  inner(
    optimize(`<svg ${WRAP}>${body}</svg>`, {
      multipass: true,
      floatPrecision: 3,
      plugins: [{ name: 'preset-default', params: { overrides: { cleanupIds: false } } }],
    }).data,
  );

/** Exact bodies for icons whose drawing must not move when Lucide is updated. */
const PINNED = {
  'nav-listFilter': '<path d="M3 6h18"/> <path d="M7 12h10"/> <path d="M10 18h4"/>',
};

const entries = [];
for (const [name, file] of Object.entries(MAP)) {
  const svg = await readFile(path.join(lucideDir, `${file}.svg`), 'utf8');
  /* The nav bar and search dialog icons (nav-*) are kept exactly as drawn. */
  const body = PINNED[name] ?? (name.startsWith('nav-') ? inner(svg) : slim(inner(svg)));
  entries.push(
    `  ${JSON.stringify(name)}: { viewBox: "0 0 24 24", body: ${JSON.stringify(body)}, stroke: true },`,
  );
}

const out = `/* Generated by scripts/generate-icons.mjs — do not edit by hand.
   Lucide (ISC, lucide.dev), 24x24 grid, optimized with SVGO. */
export const icons: Record<string, { viewBox: string; body: string; stroke?: boolean }> = {
${entries.join('\n')}
};
`;
const target = new URL('../src/lib/icons.generated.ts', import.meta.url);
await writeFile(target, out);
// `npm run lint` checks formatting across the tree, so the generated file has
// to come out the way Prettier would write it.
await promisify(execFile)('npx', ['prettier', '--write', fileURLToPath(target)]);
console.log(`wrote ${entries.length} icons`);
