/**
 * Rebuild src/lib/icons.generated.ts from lucide-static.
 *
 * Every UI icon on the site is Lucide (ISC, lucide.dev): one 24px grid, one
 * stroke, one set of terminals. Brand marks are not generated here: they are
 * the SVGs in public/uploads/, loaded by src/lib/brand-icons.ts. The two
 * `FIXED` glyphs below are the desktop nav bar's arrow and dropdown chevron,
 * kept exactly as they were drawn (Font Awesome Free, CC BY 4.0) so the nav
 * bar does not change.
 *
 *   node scripts/generate-icons.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const lucideDir = path.join(path.dirname(require.resolve('lucide-static/package.json')), 'icons');

/** site name -> Lucide icon file (icons/<file>.svg) */
const MAP = {
  rss: 'rss',
  mail: 'mail',
  envelope: 'mail',
  message: 'message-square-text',
  calendar: 'calendar-days',
  briefcase: 'briefcase-business',
  school: 'school',
  code: 'code-xml',
  users: 'users',
  sparkles: 'sparkles',
  layers: 'layers',
  trophy: 'trophy',
  bulb: 'lightbulb',
  file: 'file-text',
  pencil: 'pencil',
  help: 'circle-question-mark',
  search: 'search',
  pin: 'map-pin',
  clock: 'clock',
  cube: 'box',
  download: 'download',
  arrow: 'arrow-right',
  chevron: 'chevron-down',
  external: 'external-link',
  sun: 'sun',
  moon: 'moon',
  sunMoon: 'sun-moon',
  menu: 'menu',
  close: 'x',
  satellite: 'satellite',
  chart: 'chart-column',
  ai: 'brain-circuit',
  leaf: 'leaf',
  database: 'database',
  terminal: 'square-terminal',
  quote: 'quote',
  video: 'video',
  news: 'newspaper',
  shield: 'shield-check',
  slides: 'presentation',
  book: 'book-open',
  report: 'clipboard-check',
  preprint: 'file-clock',
  graduationCap: 'graduation-cap',
  check: 'check',
  tag: 'tag',
  copy: 'copy',
  link: 'link',
  hash: 'hash',
  reader: 'book-open-text',
  expand: 'expand',
  zoom: 'zoom-in',
  left: 'chevron-left',
  right: 'chevron-right',
  printer: 'printer',
  filePdf: 'file-down',
  filter: 'list-filter',
  info: 'info',
  pause: 'pause',
  play: 'play',
  circleArrowUp: 'circle-arrow-up',
  rocket: 'rocket',
  ellipsis: 'ellipsis',
  share: 'share-2',
  earth: 'earth',
  cpu: 'cpu',
  broom: 'broom-sparkles',
  flame: 'flame',
  flaskConical: 'flask-conical',
  plug: 'webhook',
  'nav-search': 'search',
  'nav-sun': 'sun',
  'nav-moon': 'moon',
  'nav-sunMoon': 'sun-moon',
  'nav-listFilter': 'list-filter',
  'nav-x': 'x',
  'nav-chevronRight': 'chevron-right',
};

/** Filled glyphs kept as drawn, for the desktop nav bar only. */
const FIXED = {
  'nav-arrow': {
    viewBox: '0 0 512 512',
    body: '<path fill="currentColor" d="M502.6 278.6c12.5-12.5 12.5-32.8 0-45.3l-160-160c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L402.7 224 32 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l370.7 0-105.4 105.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l160-160z"/>',
  },
  'nav-chevron': {
    viewBox: '-32 0 512 512',
    body: '<path fill="currentColor" d="M201.4 406.6c12.5 12.5 32.8 12.5 45.3 0l192-192c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L224 338.7 54.6 169.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3l192 192z"/>',
  },
};

/** The children of the <svg>, whitespace collapsed. Sliced rather than matched:
    a regex spanning the whole file backtracks for no benefit here. */
const inner = (svg) => {
  const open = svg.indexOf('>', svg.indexOf('<svg'));
  const close = svg.lastIndexOf('</svg>');
  return svg
    .slice(open + 1, close)
    .replace(/\s+/g, ' ')
    .replaceAll(' />', '/>')
    .trim();
};

const entries = [];
for (const [name, file] of Object.entries(MAP)) {
  const svg = await readFile(path.join(lucideDir, `${file}.svg`), 'utf8');
  entries.push(
    `  ${JSON.stringify(name)}: { viewBox: "0 0 24 24", body: ${JSON.stringify(inner(svg))}, stroke: true },`,
  );
}
for (const [name, g] of Object.entries(FIXED)) {
  entries.push(
    `  ${JSON.stringify(name)}: { viewBox: ${JSON.stringify(g.viewBox)}, body: ${JSON.stringify(g.body)} },`,
  );
}

const out = `/* Generated by scripts/generate-icons.mjs — do not edit by hand.
   Lucide (ISC, lucide.dev), 24x24 grid. The two nav-bar glyphs without stroke are Font Awesome Free (CC BY 4.0). */
export const icons: Record<string, { viewBox: string; body: string; stroke?: boolean }> = {
${entries.join('\n')}
};
`;
const target = new URL('../src/lib/icons.generated.ts', import.meta.url);
await writeFile(target, out);
// `npm run lint` checks formatting across the tree, so the generated file has
// to come out the way Prettier would write it.
await promisify(execFile)('npx', ['prettier', '--write', fileURLToPath(target)]);
console.log(`wrote ${entries.length} icons`);
