/**
 * Rebuild src/lib/icons.generated.ts from @fortawesome/fontawesome-free.
 *
 * Every icon on the site comes from Font Awesome Free (solid for UI marks,
 * brands for logos) so the whole set shares one weight. The SVGs are copied
 * into the repo, so nothing is fetched at runtime.
 *
 *   node scripts/generate-icons.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const svgDir = path.join(
  path.dirname(require.resolve('@fortawesome/fontawesome-free/package.json')),
  'svgs',
);

/** site name -> Font Awesome solid icon (svgs/solid/<file>.svg) */
const SOLID = {
  rss: 'rss',
  mail: 'envelope',
  envelope: 'envelope',
  message: 'message',
  calendar: 'calendar-days',
  briefcase: 'briefcase',
  school: 'school',
  code: 'code',
  users: 'users',
  sparkles: 'wand-magic-sparkles',
  layers: 'layer-group',
  trophy: 'trophy',
  bulb: 'lightbulb',
  file: 'file-lines',
  pencil: 'pencil',
  help: 'circle-question',
  search: 'magnifying-glass',
  pin: 'location-dot',
  clock: 'clock',
  cube: 'cube',
  download: 'download',
  arrow: 'arrow-right',
  chevron: 'chevron-down',
  external: 'arrow-up-right-from-square',
  sun: 'sun',
  moon: 'moon',
  sunMoon: 'circle-half-stroke',
  menu: 'bars',
  close: 'xmark',
  satellite: 'satellite',
  chart: 'chart-column',
  ai: 'brain',
  leaf: 'leaf',
  database: 'database',
  terminal: 'terminal',
  quote: 'quote-left',
  video: 'video',
  news: 'newspaper',
  shield: 'shield-halved',
  slides: 'chalkboard',
  book: 'book-open',
  report: 'clipboard-check',
  preprint: 'file-pen',
  graduationCap: 'graduation-cap',
  check: 'check',
  tag: 'tag',
  copy: 'copy',
  link: 'link',
  hash: 'hashtag',
  reader: 'book-open-reader',
  expand: 'expand',
  zoom: 'magnifying-glass-plus',
  left: 'chevron-left',
  right: 'chevron-right',
  printer: 'print',
  filePdf: 'file-pdf',
  filter: 'filter',
  info: 'circle-info',
  pause: 'pause',
  play: 'play',
  circleArrowUp: 'circle-arrow-up',
  rocket: 'rocket',
  ellipsis: 'ellipsis',
  share: 'share-nodes',
  earth: 'earth-americas',
  cpu: 'microchip',
  broom: 'broom',
  flame: 'fire',
  flaskConical: 'flask',
  plug: 'plug',
};

/** site name -> Font Awesome brand icon (svgs/brands/<file>.svg) */
const BRANDS = {
  bluesky: 'bluesky',
  facebook: 'facebook',
  github: 'github',
  linkedin: 'linkedin',
  mastodon: 'mastodon',
  orcid: 'orcid',
  pinterest: 'pinterest',
  reddit: 'reddit',
  researchgate: 'researchgate',
  scholar: 'google-scholar',
  telegram: 'telegram',
  threads: 'threads',
  tumblr: 'tumblr',
  whatsapp: 'whatsapp',
  x: 'x-twitter',
  twitter: 'x-twitter',
  'x-twitter': 'x-twitter',
};

/** { viewBox, body } — the children of the <svg>. The viewBox is padded out to
    a square (Font Awesome glyphs vary in width) so every icon sits centred in
    the same box at any size. Sliced rather than matched: a regex spanning the
    whole file backtracks for no benefit here. */
const parse = (svg) => {
  const open = svg.indexOf('>', svg.indexOf('<svg'));
  const close = svg.lastIndexOf('</svg>');
  const [x, y, w, h] = (/viewBox="([^"]+)"/.exec(svg.slice(0, open))?.[1] ?? '0 0 512 512')
    .split(/\s+/)
    .map(Number);
  const side = Math.max(w, h);
  const viewBox = [x - (side - w) / 2, y - (side - h) / 2, side, side].join(' ');
  const body = svg
    .slice(open + 1, close)
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/\s+/g, ' ')
    .replaceAll(' />', '/>')
    .trim();
  return { viewBox, body };
};

const load =
  (dir) =>
  async ([name, file]) => {
    const svg = await readFile(path.join(svgDir, dir, `${file}.svg`), 'utf8').catch(() => null);
    if (!svg) throw new Error(`No Font Awesome ${dir} icon for "${name}" (${file})`);
    const { viewBox, body } = parse(svg);
    return `  ${JSON.stringify(name)}: { viewBox: ${JSON.stringify(viewBox)}, body: ${JSON.stringify(body)} },`;
  };

const entries = [
  ...(await Promise.all(Object.entries(SOLID).map(load('solid')))),
  ...(await Promise.all(Object.entries(BRANDS).map(load('brands')))),
];

const out = `/* Generated by scripts/generate-icons.mjs — do not edit by hand.
   Font Awesome Free 7 (solid + brands), icons CC BY 4.0, https://fontawesome.com/license/free */
export const icons: Record<string, { viewBox: string; body: string }> = {
${entries.join('\n')}
};
`;
const target = new URL('../src/lib/icons.generated.ts', import.meta.url);
await writeFile(target, out);
// `npm run lint` checks formatting across the tree, so the generated file has
// to come out the way Prettier would write it.
await promisify(execFile)('npx', ['prettier', '--write', fileURLToPath(target)]);
console.log(`wrote ${entries.length} icons`);
