#!/usr/bin/env python3
"""subset-social-icons.py — shrink the share-button icon font.

The vendored quarto-social-share extension pulls in the *whole* of Font
Awesome Free 6 to draw six share buttons: a 101 KiB stylesheet plus, at
runtime, fa-brands-400.woff2 (116 KiB) and fa-solid-900.woff2 (153 KiB). Every
page under blog/, projects/, publications/, awards/, education/ and interests/
paid that ~370 KiB.

This script regenerates a subset — same font families, same glyph outlines, so
the buttons render identically — containing only the icons the site actually
uses, and a matching stylesheet with only the rules those icons need. Output
lands next to the extension:

    _extensions/schochastics/social-share/social-share-icons.css
    _extensions/schochastics/social-share/webfonts/fa-{brands,solid}-subset.woff2

`social-share.lua` is patched (by hand, once) to load that stylesheet instead
of upstream's all.min.css. The upstream files are left untouched so reverting
is a one-line change in the Lua filter.

This is a maintenance script, not a build step: the generated files are
committed and `quarto render` remains the only thing CI runs.

    pip install fonttools brotli
    python3 scripts/subset-social-icons.py

If you enable another network in a `_metadata.yml` `share:` block, add its
icon to ICONS below and re-run — otherwise that button renders as a blank box.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
EXT = ROOT / "_extensions" / "schochastics" / "social-share"
UPSTREAM = EXT / "_extensions" / "quarto-ext" / "fontawesome" / "assets"
OUT_CSS = EXT / "social-share-icons.css"
OUT_FONTS = EXT / "webfonts"

# Icon class -> family, keyed by the `share:` options enabled in the site's
# `_metadata.yml` files (twitter, linkedin, email, facebook, reddit, bsky).
# The class names come straight out of social-share.lua.
ICONS = {
    "x-twitter": "brands",  # share.twitter
    "linkedin-in": "brands",  # share.linkedin
    "facebook-f": "brands",  # share.facebook
    "reddit-alien": "brands",  # share.reddit
    "bluesky": "brands",  # share.bsky
    "envelope": "solid",  # share.email
}

FAMILY = {"brands": "Font Awesome 6 Brands", "solid": "Font Awesome 6 Free"}
WEIGHT = {"brands": "400", "solid": "900"}
SOURCE_WOFF2 = {"brands": "fa-brands-400.woff2", "solid": "fa-solid-900.woff2"}


def codepoints(css: str) -> dict[str, int]:
    """Pull each icon's private-use codepoint out of upstream's stylesheet."""
    found = {}
    for name in ICONS:
        m = re.search(r"\.fa-%s:before\{content:\"\\([0-9a-f]+)\"\}" % re.escape(name), css)
        if not m:
            sys.exit(f"[social-icons] .fa-{name} not found in all.min.css")
        found[name] = int(m.group(1), 16)
    return found


def write_subset(kind: str, cps: list[int]) -> tuple[Path, int, int]:
    src = UPSTREAM / "webfonts" / SOURCE_WOFF2[kind]
    dst = OUT_FONTS / f"fa-{kind}-subset.woff2"
    font = TTFont(src)
    options = subset.Options()
    # Keep it to outlines: no layout tables, no hinting, no name records that
    # only matter to font pickers. The glyphs themselves are byte-identical.
    options.layout_features = []
    options.hinting = False
    options.desubroutinize = True
    options.name_IDs = []
    options.notdef_outline = False
    options.drop_tables += ["GSUB", "GPOS", "GDEF", "DSIG"]
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=cps)
    subsetter.subset(font)
    font.flavor = "woff2"
    dst.parent.mkdir(parents=True, exist_ok=True)
    font.save(dst)
    return dst, src.stat().st_size, dst.stat().st_size


def main() -> None:
    upstream_css = (UPSTREAM / "css" / "all.min.css").read_text(encoding="utf8")
    cps = codepoints(upstream_css)

    lines = [
        "/* Generated by scripts/subset-social-icons.py — do not edit by hand.",
        " *",
        " * A subset of Font Awesome Free 6.5.2 (Icons: CC BY 4.0, Fonts: SIL OFL 1.1,",
        " * Code: MIT — https://fontawesome.com/license/free) carrying only the glyphs",
        " * quarto-social-share draws on this site. Replaces the extension's bundled",
        " * all.min.css; see the comment in social-share.lua.",
        " */",
    ]

    for kind in ("brands", "solid"):
        used = [cps[n] for n, k in ICONS.items() if k == kind]
        if not used:
            continue
        dst, before, after = write_subset(kind, used)
        print(f"[social-icons] {dst.name}: {before // 1024} KiB -> {after / 1024:.1f} KiB")
        lines.append(
            "@font-face{font-family:\"%s\";font-style:normal;font-weight:%s;"
            "font-display:block;src:url(webfonts/%s) format(\"woff2\")}"
            % (FAMILY[kind], WEIGHT[kind], dst.name)
        )

    # Shared base rules, matching upstream's for the selectors the filter emits
    # (`fa-brands`, `fab`, `fa-solid`, plus the fa-fw/fa-lg sizing utilities).
    lines += [
        ".fa-brands,.fa-solid,.fab,.fas{-moz-osx-font-smoothing:grayscale;"
        "-webkit-font-smoothing:antialiased;display:var(--fa-display,inline-block);"
        "font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}",
        '.fa-solid,.fas{font-family:"Font Awesome 6 Free";font-weight:900}',
        '.fa-brands,.fab{font-family:"Font Awesome 6 Brands";font-weight:400}',
        ".fa-fw{text-align:center;width:1.25em}",
        ".fa-lg{font-size:1.25em;line-height:.05em;vertical-align:-.075em}",
    ]
    for name in ICONS:
        lines.append('.fa-%s:before{content:"\\%04x"}' % (name, cps[name]))

    OUT_CSS.write_text("\n".join(lines) + "\n", encoding="utf8")
    upstream_size = len(upstream_css.encode("utf8"))
    print(
        f"[social-icons] {OUT_CSS.name}: {upstream_size // 1024} KiB -> "
        f"{OUT_CSS.stat().st_size / 1024:.1f} KiB"
    )


if __name__ == "__main__":
    main()
