---
title: "Fire at the fringe: Drivers of large wildfires in and near the wildland-urban interface of the eastern United States"
date: "2025-04-01"
description: "Large wildfires are increasing in the eastern U.S., which contains the greatest amount of WUI compared to the rest of the country. Wildfires in and near the WUI pose the greatest risk to human life and property. However, the spatial…"
categories: ["Presentation"]
pub-authors: "**Weidig, N. C.**, Wonkka, C. L., Ivey, M. A., Johnson, D. J. & Donovan, V. M."
pub-venue: "International Association for Landscape Ecology - North America Annual Conference"
pub-url: "https://www.ialena.org/uploads/9/4/8/2/94821076/iale_program_handout_final.pdf"
---

::: {.nw-cite-meta}
**Weidig, N. C.**, Wonkka, C. L., Ivey, M. A., Johnson, D. J. & Donovan, V. M. (2025). *International Association for Landscape Ecology - North America Annual Conference*.
:::

[Source](https://www.ialena.org/uploads/9/4/8/2/94821076/iale_program_handout_final.pdf){.nw-btn .nw-btn-primary target="_blank"} [BibTeX](cite.bib){.nw-btn .nw-btn-ghost}

## Abstract

Large wildfires are increasing in the eastern U.S., which contains the greatest amount of WUI compared to the rest of the country. Wildfires in and near the WUI pose the greatest risk to human life and property. However, the spatial relationship between large wildfires and the WUI in the eastern U.S., as well as which factors drive these patterns, remains unclear. Using large wildfire (>200 ha) data from 1991 and 2021, we (1) assessed the spatial relationships of large wildfires relative to the WUI and (2) modeled these relationships using a variety of social and environmental variables at multiple spatial scales. Specifically, we assessed wildfire WUI status (intersecting or outside the WUI), distance to WUI, and proportion of WUI area burned. We found that fewer wildfires burned in the WUI compared to a random distribution. Wildfires that intersected the WUI burned either a very small or very large proportion of the WUI; however, wildfires outside the WUI burned closer to it than expected at random. At the largest spatial scale, our global model containing weather, fuel, ignition, and suppression-related variables best explained the relationship between wildfires and the WUI. Overall, wildfires in the WUI burned in areas with higher woody cover, more suppression resources nearby, higher road density, lower precipitation, lower wind speed and during times when suppression resources were more strained than wildfires outside the WUI. Wildfires that burned a larger proportion of the WUI or burned closer to the WUI experienced similar trends compared to wildfires that burned a smaller proportion of the WUI or burned farther from the WUI. At the regional scale, factors driving these relationships varied among eastern ecoregions. Our findings highlight the need for region-specific wildfire risk management and improved fire suppression planning.
